# Generated by Django 4.1.7 on 2023-03-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomski', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='course',
            name='profesor_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
